blogger/note/urls.py
# -*- coding: utf-8 -*-
#
# Copyright 2015 Yeolar
#

from django.conf.urls import url

from .views import *


urlpatterns = [
    # operation
    url(r'^topic/set/(?P<id>\d+)/$',
        topic_set,
        name='note_topic_set'
    ),
    url(r'^topic/set/$',
        topic_set,
        name='note_topic_set'
    ),
    url(r'^post/set/(?P<id>\d+)/$',
        post_set,
        name='note_post_set'
    ),
    url(r'^post/set/$',
        post_set,
        name='note_post_set'
    ),
    # date
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(),
        name='note_detail'
    ),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        PostDayArchiveView.as_view(),
        name='note_archive_day'
    ),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        PostMonthArchiveView.as_view(),
        name='note_archive_month'
    ),
    url(r'^(?P<year>\d{4})/$',
        PostYearArchiveView.as_view(),
        name='note_archive_year'
    ),
    # list
    url(r'^privates/$',
        PrivateListView.as_view(),
        name='note_private_list'
    ),
    url(r'^drafts/$',
        DraftListView.as_view(),
        name='note_draft_list'
    ),
    # topic
    url(r'^topics/(?P<id>\d+)/$',
        TopicDetailView.as_view(),
        name='note_topic_detail'
    ),
    url (r'^topics/$',
        TopicListView.as_view(),
        name='note_topic_list'
    ),
    # misc
    url(r'^search/$',
        search,
        name='note_search'
    ),
    url(r'^$',
        PostListView.as_view(),
        name='note_index'
    ),
]

blogger/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('blogger.accounts.urls')),
    url(r'^fileupload/', include('blogger.fileupload.urls')),
    url(r'^note/', include('blogger.note.urls')),
    url(r'^', include('blogger.home.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogger/note/models.py
# -*- coding: utf-8 -*-
#
# Copyright 2015 Yeolar
#

from datetime import datetime

from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User

from BeautifulSoup import BeautifulSoup

from .managers import TopicManager, PostManager


class Topic(models.Model):

    name = models.CharField(u'名称', max_length=100, unique=True)
    desc = models.TextField(u'描述', blank=True)
    contents = models.TextField(u'目录', blank=True)
    weight = models.IntegerField(u'权重', default=0)
    public = models.BooleanField(u'公开', editable=False, default=False)

    objects = TopicManager()

    class Meta:
        verbose_name = u'主题'
        verbose_name_plural = u'主题'
        db_table = 'note_topics'
        ordering = ('-weight', 'name')
        get_latest_by = 'weight'

    def __unicode__(self):
        return u'%s' % self.name

    @permalink
    def get_absolute_url(self):
        return ('note_topic_detail', None, {'id': self.id})


class Post(models.Model):

    STATUS_CHOICES = ((1, u'草稿'), (2, u'私有'), (3, u'公开'))

    title = models.CharField(u'标题', max_length=200)
    slug = models.SlugField(u'别名', unique_for_date='publish')
    author = models.ForeignKey(User, verbose_name=u'作者')
    text = models.TextField(u'文本')
    publish = models.DateTimeField(u'发布时间', default=datetime.now)
    status = models.IntegerField(u'状态', choices=STATUS_CHOICES, default=3)
    topic = models.ForeignKey(Topic,
            verbose_name=u'主题', blank=True, null=True)

    objects = PostManager()

    class Meta:
        verbose_name = u'文章'
        verbose_name_plural = u'文章'
        db_table = 'note_posts'
        ordering = ('-publish',)
        get_latest_by = 'publish'

    def __unicode__(self):
        return u'%s' % self.title

    def readable_str(self):
        return u'%4s:%s (%s)' % (self.id, self.get_absolute_url(), self.title)

    @permalink
    def get_absolute_url(self):
        return ('note_detail', None, {
            'year': self.publish.year,
            'month': self.publish.strftime('%m'),
            'day': self.publish.strftime('%d'),
            'slug': self.slug
        })

    def link(self):
        return '<a href="%s">%s</a>' % (self.get_absolute_url(), u'查看')
    link.allow_tags = True

    @property
    def html_short(self):
        return unicode(BeautifulSoup(self.text[:100]))

    def get_previous_post_su(self):
        return self.get_previous_by_publish(status__gte=2)

    def get_previous_post(self):
        return self.get_previous_by_publish(status__exact=3)

    def get_next_post_su(self):
        return self.get_next_by_publish(status__gte=2)

    def get_next_post(self):
        return self.get_next_by_publish(status__exact=3)

    def get_previous_topic_post_su(self):
        return self.get_previous_by_publish(status__gte=2, topic=self.topic)

    def get_previous_topic_post(self):
        return self.get_previous_by_publish(status__exact=3, topic=self.topic)

    def get_next_topic_post_su(self):
        return self.get_next_by_publish(status__gte=2, topic=self.topic)

    def get_next_topic_post(self):
        return self.get_next_by_publish(status__exact=3, topic=self.topic)

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)
        if self.topic:
            self.topic.public = (len(self.topic.post_set.public()) != 0)
            self.topic.save()

    def delete(self, *args, **kwargs):
        super(Post, self).delete(*args, **kwargs)
        if self.topic:
            self.topic.public = (len(self.topic.post_set.public()) != 0)
            self.topic.save()

blogger/note/forms.py
# -*- coding: utf-8 -*-
#
# Copyright 2018 Yeolar
#

from django.forms import ModelForm
from django.forms import HiddenInput, TextInput, Select, Textarea

from .models import *


class TopicForm(ModelForm):

    required_css_class = 'required'
    error_css_class = 'error'

    class Meta:
        model = Topic
        fields = ('name', 'desc', 'contents', 'weight')
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': u'主题',
                }),
            'desc': Textarea(attrs={'class': 'form-control input-sm'}),
            'contents': Textarea(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': u'目录',
                }),
            'weight': TextInput(attrs={'class': 'form-control input-sm'}),
        }


class PostForm(ModelForm):

    required_css_class = 'required'
    error_css_class = 'error'

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author')
        super(PostForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(PostForm, self).save(commit=False)
        instance.author = self.author
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Post
        fields = ('title', 'slug', 'text', 'publish', 'status', 'topic')
        widgets = {
            'title': TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'placeholder': u'标题',
                    'onkeyup': 'calcHash()'
                }),
            'slug': HiddenInput(attrs={'class': 'form-control input-sm'}),
            'text': Textarea(attrs={'class': 'form-control input-sm'}),
            'publish': TextInput(attrs={'class': 'form-control input-sm'}),
            'status': Select(attrs={'class': 'form-control input-sm'}),
            'topic': Select(attrs={'class': 'form-control input-sm'}),
        }

blogger/note/views.py
# -*- coding: utf-8 -*-
#
# Copyright 2015 Yeolar
#

from datetime import datetime

from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.utils.decorators import method_decorator
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.dates import YearArchiveView, MonthArchiveView, DayArchiveView, DateDetailView
from django.db.models import Q
from django.conf import settings

from .models import *
from .forms import *
from ..util.search.constants import STOP_WORDS_RE
from ..util.decorators import superuser_required


@superuser_required
def topic_set(request, id=None, **kwargs):
    if id:
        topic = Topic.objects.get(id=id)
    else:
        topic = Topic()

    if request.method == 'POST':
        form = TopicForm(request.POST, instance=topic)

        if form.is_valid():
            topic = form.save()
            return redirect(topic.get_absolute_url())
    else:
        form = TopicForm(instance=topic)

    return render_to_response(
            'note/topic_set.html',
            {'form': form, 'id': id},
            RequestContext(request))   # use for csrf


@superuser_required
def post_set(request, id=None, **kwargs):
    if id:
        post = Post.objects.get(id=id)
    else:
        post = Post()

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post, author=request.user)

        if form.is_valid():
            post = form.save()
            return redirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post, author=request.user)
        form.fields['topic'].queryset = Topic.objects.all()

    return render_to_response(
            'note/post_set.html',
            {'form': form, 'id': id},
            RequestContext(request))   # use for csrf


class TopicListView(ListView):

    def get_queryset(self):
        if self.request.user.is_superuser:
            self.topics = Topic.objects.all()
        else:
            self.topics = Topic.objects.public()
        return self.topics

    def get_context_data(self, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': self.topics[:5],
        })
        return context


class TopicDetailView(ListView):

    paginate_by = getattr(settings, 'NOTE_PAGESIZE', 20)
    template_name = 'note/topic_detail.html'

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, id=self.kwargs['id'])
        if self.request.user.is_superuser:
            return self.topic.post_set.published()
        else:
            return self.topic.post_set.public()

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            topics = Topic.objects.all()
        else:
            topics = Topic.objects.public()
        context = super(TopicDetailView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': topics[:5],
            'topic': self.topic
        })
        return context


class PostListView(ListView):

    paginate_by = getattr(settings, 'NOTE_PAGESIZE', 20)

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.all()
        else:
            return Post.objects.public()

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            topics = Topic.objects.all()
        else:
            topics = Topic.objects.public()
        context = super(PostListView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': topics[:5],
        })
        return context


class PrivateListView(ListView):

    paginate_by = getattr(settings, 'NOTE_PAGESIZE', 20)
    template_name = 'note/private_list.html'

    @method_decorator(superuser_required)
    def dispatch(self, *args, **kwargs):
        return super(PrivateListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Post.objects.private()

    def get_context_data(self, **kwargs):
        context = super(PrivateListView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': Topic.objects.all()[:5],
        })
        return context


class DraftListView(ListView):

    paginate_by = getattr(settings, 'NOTE_PAGESIZE', 20)
    template_name = 'note/draft_list.html'

    @method_decorator(superuser_required)
    def dispatch(self, *args, **kwargs):
        return super(DraftListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Post.objects.draft()

    def get_context_data(self, **kwargs):
        context = super(DraftListView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': Topic.objects.all()[:5],
        })
        return context


class PostYearArchiveView(YearArchiveView):

    date_field = 'publish'
    make_object_list = True

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.published()
        else:
            return Post.objects.public()

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            topics = Topic.objects.all()
        else:
            topics = Topic.objects.public()
        context = super(PostYearArchiveView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': topics[:5],
        })
        return context


class PostMonthArchiveView(MonthArchiveView):

    date_field = 'publish'
    month_format = '%m'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.published()
        else:
            return Post.objects.public()

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            topics = Topic.objects.all()
        else:
            topics = Topic.objects.public()
        context = super(PostMonthArchiveView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': topics[:5],
        })
        return context


class PostDayArchiveView(DayArchiveView):

    date_field = 'publish'
    month_format = '%m'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.published()
        else:
            return Post.objects.public()

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            topics = Topic.objects.all()
        else:
            topics = Topic.objects.public()
        context = super(PostDayArchiveView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': topics[:5],
        })
        return context


class PostDetailView(DateDetailView):

    month_format = '%m'
    date_field = 'publish'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.all()  # show draft for preview
        else:
            return Post.objects.public()

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            topics = Topic.objects.all()
        else:
            topics = Topic.objects.public()
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context.update({
            'topic_list': topics[:5],
        })
        return context


def search(request, paginate_by=10,
        template_name='note/post_search.html', **kwargs):
    page_size = getattr(settings,'SEARCH_PAGESIZE', paginate_by)

    if request.GET:
        if request.user.is_superuser:
            posts = Post.objects.published()
            topics = Topic.objects.all()
        else:
            posts = Post.objects.public()
            topics = Topic.objects.public()

        context = {
            'topic_list': topics[:5],
        }

        vague_terms = True
        stop_word_list = STOP_WORDS_RE
        search_terms = '%s' % request.GET['q']
        search_term_list = search_terms.split()
        cleaned_search_term_list = []
        for search_term in search_term_list:
            cleaned_search_term = stop_word_list.sub('', search_term)
            cleaned_search_term = cleaned_search_term.strip()
            if len(cleaned_search_term) != 0:
                cleaned_search_term_list.append(cleaned_search_term)
                posts = posts.filter(
                        Q(title__icontains=cleaned_search_term) |
                        Q(author__username__icontains=cleaned_search_term) |
                        Q(text__icontains=cleaned_search_term))
                vague_terms = False

        if not vague_terms:
            if len(posts) != 0:
                paginator = Paginator(posts, page_size)
                try:
                    page = int(request.GET.get('page', '1'))
                except ValueError:
                    page = 1
                try:
                    objects = paginator.page(page)
                except EmptyPage, InvalidPage:
                    objects = paginator.page(paginator.num_pages)
                context.update({
                    'paged_objects': objects,
                    'search_terms': search_terms,
                    'cleaned_search_terms': ' '.join(cleaned_search_term_list)
                })
            else:
                message = u'结果未找到。'
                context.update({'message': message})
        else:
            message = u'搜索条件太简单，请调整。'
            context.update({'message': message})

    return render_to_response(template_name, context, RequestContext(request))

templates/note/base_list.html
{% extends "note/base_note.html" %}

{% block list_nav_active %} class="active"{% endblock %}

{% block content %}
<div id="content">
  {% if is_paginated %}
    <ul class="pagination pagination-sm pull-right">
      {% if page_obj.has_next %}
      <li><a href="?page=last"><i class="icon-double-angle-left"></i></a></li>
      <li><a href="?page={{ page_obj.next_page_number }}"><i class="icon-angle-left"></i></a></li>
      {% else %}
      <li class="disabled"><span><i class="icon-double-angle-left"></i></span></li>
      <li class="disabled"><span><i class="icon-angle-left"></i></span></li>
      {% endif %}
      <li class="info"><span>{{ page_obj.number }}/{{ paginator.num_pages }}</span></li>
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}"><i class="icon-angle-right"></i></a></li>
      <li><a href="?page=1"><i class="icon-double-angle-right"></i></a></li>
      {% else %}
      <li class="disabled"><span><i class="icon-angle-right"></i></span></li>
      <li class="disabled"><span><i class="icon-double-angle-right"></i></span></li>
      {% endif %}
    </ul>
  {% endif %}

  {% if object_list %}
    {% block post_list %}
    <table class="table table-condensed table-hover table-hide-overflow">
      <thead>
        <tr><th class="col-sm-9"></th>
            <th class="col-sm-3"></th>
        </tr>
      </thead>
      <tbody>
        {% for post in object_list %}
        <tr{% ifequal post.status 1 %} class="danger"{% endifequal %}{% ifequal post.status 2 %} class="success"{% endifequal %}>
          <td><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title }}</a></td>
          <td>{{ post.publish|date:"Y-m-d H:i" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endblock %}
  {% else %}
    {% if message %}
    <div class="alert alert-success">{{ message }}</div>
    {% else %}
    <div class="alert alert-success">没有文章存在或可见。</div>
    {% endif %}
  {% endif %}
</div>
{% endblock %}

templates/note/base_note.html
{% extends "base.html" %}

templates/note/draft_list.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; 草稿列表{% endblock %}

{% block list_nav_active %}{% endblock %}
{% block draft_nav_active %} class="active"{% endblock %}

templates/note/post_archive_day.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; {{ day|date:"Y-m-d" }}{% endblock %}

templates/note/post_archive_month.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; {{ month|date:"Y.m" }}{% endblock %}

templates/note/post_archive_year.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; {{ year }}{% endblock %}

templates/note/post_list.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; 文章列表{% endblock %}

templates/note/post_search.html
{% extends "note/base_note.html" %}

{% load searchtags %}

{% block title %}{{ block.super }} &raquo; 搜索结果{% endblock %}
{% block script %}
<script>
function highlight(e, text, className) {
    var val = e.html();
    var pos = val.toLowerCase().indexOf(text.toLowerCase());
    if (pos >= 0) {
        var span = $('<span></span>');
        span.addClass(className);
        span.html(val.substr(pos, text.length));
        e.html(val.substr(0, pos));
        e.append(span);
        e.append(val.substr(pos + text.length));
    }
}
$(document).ready(function() {
    $('#search-post a#title, #search-post div#summary, #search-post span#author').each(function() {
        var keys = '{{ cleaned_search_terms }}'.split(' ');
        for (var i = 0; i < keys.length; i++) {
            highlight($(this), keys[i], 'highlight');
        }
    });
});
</script>
{% endblock %}

{% block content %}
<div id="content">
  {% if paged_objects.object_list %}
    {% for post in paged_objects.object_list %}
    <div id="search-post">
      <div>
        <a id="title" href="{{ post.get_absolute_url }}">{{ post.title|cut_text:80 }}</a>
      </div>
      <div id="summary">
      {{ post.text|safe|search_summary:cleaned_search_terms }}
      </div>
      <div class="text-success">
        <span id="date">{{ post.publish|date:"Y-m-d H:i" }}</span>
      </div>
    </div>
    {% endfor %}
  {% else %}
    {% if message %}
    <div class="alert alert-success">{{ message }}</div>
    {% else %}
    <div class="alert alert-success">没有文章存在或可见。</div>
    {% endif %}
  {% endif %}

  {% if paged_objects.paginator.num_pages > 1 %}
    <ul class="pagination pagination-sm pull-right">
      {% if paged_objects.has_next %}
      <li><a href="?q={{ search_terms }}&page=last"><i class="icon-double-angle-left"></i></a></li>
      <li><a href="?q={{ search_terms }}&page={{ paged_objects.next_page_number }}"><i class="icon-angle-left"></i></a></li>
      {% else %}
      <li class="disabled"><span><i class="icon-double-angle-left"></i></span></li>
      <li class="disabled"><span><i class="icon-angle-left"></i></span></li>
      {% endif %}
      <li class="info"><span>{{ paged_objects.number }}/{{ paged_objects.paginator.num_pages }}</span></li>
      {% if paged_objects.has_previous %}
      <li><a href="?q={{ search_terms }}&page={{ paged_objects.previous_page_number }}"><i class="icon-angle-right"></i></a></li>
      <li><a href="?q={{ search_terms }}&page=1"><i class="icon-double-angle-right"></i></a></li>
      {% else %}
      <li class="disabled"><span><i class="icon-angle-right"></i></span></li>
      <li class="disabled"><span><i class="icon-double-angle-right"></i></span></li>
      {% endif %}
    </ul>
  {% endif %}
</div>
{% endblock %}

templates/note/post_set.html
{% extends "note/base_note.html" %}
{% load static %}

{% block title %}{% if id %}修改{% else %}创建{% endif %}{% endblock %}

{% block style %}
<style type='text/css'>
.form-group {
  margin-bottom: 5px;
}
.btn-default {
  margin-right: 8px;
}
#form-input {
  margin: 20px 0;
}
#id_title, #id_topic, #id_publish, #id_status {
  height: 34px;
  font-size: 1em;
  line-height: 1.42857143;
}
.ck-editor__editable {
  min-height: 400px;
}
</style>
{% endblock %}

{% block script %}
<script src="{% static "o/js/sha.js" %}"></script>
<script src="{% static "ckeditor5/ckeditor.js" %}"></script>
<script>
function calcHash() {
    {% if not id %}
    var hash = new jsSHA($('#id_title').val() + $('#id_publish').val(), 'TEXT');
    $('#id_slug').val(hash.getHash('SHA-1', 'HEX', 1).slice(0, 10));
    {% endif %}
}
$(function() {
ClassicEditor
    .create( document.querySelector( '#id_text' ), {
        language: 'zh-cn',
        ckfinder: {
            uploadUrl: '/fileupload/upload/'
        }
    } )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
});
</script>
{% endblock %}

{% block content %}
<div id="content">
<form class="form-horizontal" role="form" action="{% if id %}{% url 'note_post_set' id %}{% else %}{% url 'note_post_set' %}{% endif %}" method="POST">{% csrf_token %}
  <div id="form-input">
  <div class="form-group">
    <div class="col-sm-8">{{ form.title }}</div>
    <div class="col-sm-0">{{ form.slug }}</div>
    <div class="col-sm-4">{{ form.topic }}</div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">{{ form.text }}</div>
  </div>
  <div class="form-group">
    <div class="col-sm-3">{{ form.publish }}</div>
    <div class="col-sm-2">{{ form.status }}</div>
    <div class="col-sm-7">
      <button class="btn btn-primary pull-right" type="submit">保存</button>
    </div>
  </div>
  </div>
</form>
</div>
{% endblock %}

templates/note/private_list.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; 私有文章列表{% endblock %}

{% block list_nav_active %}{% endblock %}
{% block private_nav_active %} class="active"{% endblock %}

templates/note/topic_detail.html
{% extends "note/base_list.html" %}

{% block title %}{{ block.super }} &raquo; {{ topic }}{% endblock %}

{% block list_nav_active %}{% endblock %}

{% block navbar_right %}
<ul class="nav navbar-nav navbar-right">
  {% if user.is_superuser %}
  <li><a href="/note/topic/set/{{ topic.id }}"><i class="icon-plus"></i></a></li>
  <li><a href="/note/post/set/"><i class="icon-pencil"></i></a></li>
  <li><a href="/admin/"><i class="icon-user"></i></a></li>
  <li><a href="/accounts/logout/"><i class="icon-signout"></i></a></li>
  {% else %}
  <li><a href="/accounts/login/"><i class="icon-signin"></i></a></li>
  {% endif %}
</ul>
{% endblock %}

templates/note/topic_set.html
{% extends "note/base_note.html" %}
{% load static %}

{% block title %}{% if id %}修改{% else %}创建{% endif %}{% endblock %}

{% block style %}
<style type='text/css'>
.form-group {
  margin-bottom: 5px;
}
.btn-default {
  margin-right: 8px;
}
#form-input {
  margin: 20px 0;
}
#id_name, #id_weight {
  height: 34px;
  font-size: 1em;
  line-height: 1.42857143;
}
#id_contents {
  height: 300px;
  font-size: 1em;
}
.ck-editor__editable {
  min-height: 95px;
}
</style>
{% endblock %}

{% block script %}
<script src="{% static "ckeditor5/ckeditor.js" %}"></script>
<script>
$(function() {
ClassicEditor
    .create( document.querySelector( '#id_desc' ), {
        language: 'zh-cn',
        ckfinder: {
            uploadUrl: '/fileupload/upload/'
        }
    } )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
});
</script>
{% endblock %}

{% block content %}
<div id="content">
<form class="form-horizontal" role="form" action="{% if id %}{% url 'note_topic_set' id %}{% else %}{% url 'note_topic_set' %}{% endif %}" method="POST">{% csrf_token %}
  <div id="form-input">
  <div class="form-group">
    <div class="col-sm-12">{{ form.name }}</div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">{{ form.desc }}</div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">{{ form.contents }}</div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">{{ form.weight }}</div>
    <div class="col-sm-10">
      <button class="btn btn-primary pull-right" type="submit">保存</button>
    </div>
  </div>
  </div>
</form>
</div>
{% endblock %}